<<<<<<< HEAD
# Generated by Django 3.2.15 on 2022-09-09 14:35
=======
# Generated by Django 3.2.15 on 2022-09-09 07:02
>>>>>>> eb54dfea0550d106f8f5186f02f53d2a8b0dba08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
